---

- block:

  - name: Install rustup and cargo
    ansible.builtin.shell:
      cmd: curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
      chdir: "{{ exp_code_dir }}/cohere-dpolicy"
      executable: /bin/bash
      creates: ~/.cargo/bin/rustup


  - name: Install Rust Version
    ansible.builtin.shell:
      cmd: ~/.cargo/bin/rustup install {{ rust_version }} && ~/.cargo/bin/rustup override set {{ rust_version }}
      executable: /bin/bash
      chdir: "{{ exp_code_dir }}/cohere-dpolicy"

  - name: Build the DP-Planner
    ansible.builtin.shell:
      cmd: "{{ cargo_loc }} build --release"
      executable: /bin/bash
      chdir: "{{ exp_code_dir }}/cohere-dpolicy"
    environment:
      GUROBI_HOME: "{{ gurobi.home }}"
      LD_LIBRARY_PATH: "{{ gurobi.ld_library_path }}"

  - name: Copy Gurobi Config
    ansible.builtin.copy:
      src: "{{ does_config_dir }}/gurobi_config/"
      dest: "{{ data_dir }}"

  - name: Copy Gurobi License
    ansible.builtin.copy:
      src: "{{ does_config_dir }}/upload/gurobi.lic"
      dest: "{{ gurobi.license_dir }}"

  when: play_hosts.index(inventory_hostname) | int == 0 # only execute for first host overall